Vagrant.configure("2") do |config|
  config.vm.synced_folder "..", "/home/vagrant/src/memory"
  config.vm.provision "shell", path: "provision.sh", keep_color: true

  config.vm.define "focal" do |focal|
    focal.vm.box = "bento/ubuntu-20.04"
  end

  config.vm.define "bionic" do |bionic|
    bionic.vm.box = "bento/ubuntu-18.04"
  end

  config.vm.define "xenial" do |xenial|
    xenial.vm.box = "bento/ubuntu-16.04"
  end

  config.vm.define "trusty" do |trusty|
    trusty.vm.box = "bento/ubuntu-14.04"
  end
end
